version: '3.8'

services:

  web:
    build:
      context: ./ccm_web/
      args:
        - PORT=3333 # This is also the default.
      target: base
    working_dir: /base/
    environment:
      - PORT=3333
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - 3333:3333
    volumes:
      # Facilitates re-loading
      - ./ccm_web/:/base/:z
      # Prevents node_modules from being copied from repo into container
      - /base/node_modules/
    command: npm run dev -- -p 3333
    container_name: ccm_web
