version: '3.8'

services:

  web:
    build:
      context: ./ccm_web/
    environment:
      - PORT=3333
      - NODE_ENV=development
    ports:
      - 3333:3333
      # Added to eliminate repeated console errors.
      # I need to look into this more. Seems like only a dev environment problem.
      # https://github.com/sveltejs/sapper-template/issues/175
      - 10000:10000
    volumes:
      # Facilitates re-loading
      - ./ccm_web/src:/app/src:z
      - ./ccm_web/static:/app/static:z
    container_name: ccm_web
