version: '3.8'

services:

  web:
    build:
      context: ./ccm_web/
      args:
        - PORT=4000
    environment:
      - PORT=4000
      - NODE_ENV=production
    env_file: .env
    ports:
      - 4000:4000
    container_name: ccm_web_prod
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=ccm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5400:5432
    volumes:
      - .postgres_data_prod:/var/lib/postgresql/data
    container_name: ccm_db_prod
